name: 🐛 Bug Report
description: Open an issue about a bug that needs fixing.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have written a descriptive issue title.
          required: true
        - label: I have searched all issues/PRs to ensure it has not already been reported or fixed.
          required: true
        - label: I have verified that I am using the latest version of Scoop and corresponding bucket.
          required: true
  - type: input
    attributes:
      label: Package Name
      description: Name of package (install name) which has bug(s)
      placeholder: e.g. abgox.PSCompletions (not 'PSCompletions')
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected/Current Behaviour
      description: A clear and concise description of what you expected to happen and what actually happen.
      placeholder: I am experiencing a problem with X. I think Y should be happening but Z is actually happening.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: List of steps, sample code or failing test that reproduces the behavior.
      render: console
      placeholder: |
        PS> scoop install abyss/abgox.InputTip-zip
        Installing 'abgox.InputTip-zip' (2025.10.01) [64bit] from 'abyss' bucket
        Loading 2c4b97ed363ef65df59161abdc0d9f1285964afe.zip from cache
        Checking hash of 2c4b97ed363ef65df59161abdc0d9f1285964afe.zip ... ok.
        Extracting 2c4b97ed363ef65df59161abdc0d9f1285964afe.zip ... done.
        Running pre_install script...
        done.
        Linking D:\@scoop\apps\abgox.InputTip-zip\current => D:\@scoop\apps\abgox.InputTip-zip\2025.10.01
        Creating shim for 'InputTip'.
        Making D:\@scoop\shims\inputtip.exe a GUI binary.
        Creating shortcut for InputTip (AutoHotkey64.exe) failed: Couldn't find icon D:\@scoop\apps\abgox.InputTip-zip\current\src\InputTipIcon\app.ico

    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible Solution
      description: Do you have some suggestions on a fix for the bug?
      placeholder: I am experiencing a problem with X. I think Y should be happening but Z is actually happening.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Scoop and Buckets Version
      description: Paste verbatim output from `scoop --version` below.
      render: console
      placeholder: |
        PS> scoop --version
        Current Scoop version:
        ca0506cf (HEAD -> develop, origin/develop) refactor(output): Replace raw prints with functions for standardized output (#6449)

        'main' bucket:
        86ce80177 (HEAD -> master, origin/master, origin/HEAD) whisper-cpp: Update to version 1.8.0

        'abyss' bucket:
        4256499 (HEAD -> main, origin/main, origin/HEAD) (chore): automatically update some content
    validations:
      required: true
  - type: textarea
    attributes:
      label: Scoop Config
      description: Paste verbatim output from `scoop config` below.
      render: console
      placeholder: |
        PS> scoop config

        last_update            : 2025/10/01 21:00:00
        scoop_repo             : https://gitee.com/scoop-installer-mirrors/Scoop
        scoop_branch           : develop
        use_lessmsi            : True
        aria2-enabled          : True
        aria2-warning-enabled  : False
    validations:
      required: true
  - type: textarea
    attributes:
      label: PowerShell Version
      description: Paste verbatim output from `$PSVersionTable` below.
      render: console
      placeholder: |
        PS> $PSVersionTable

        Name                           Value
        ----                           -----
        PSVersion                      7.5.3
        PSEdition                      Core
        GitCommitId                    7.5.3
        OS                             Microsoft Windows 10.0.26100
        Platform                       Win32NT
        PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
        PSRemotingProtocolVersion      2.3
        SerializationVersion           1.1.0.1
        WSManStackVersion              3.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Softwares
      description: List any additional software that you are using and may be related to this bug.
    validations:
      required: false
