# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
blank_issues_enabled: true
faq:
  - name: Frequently Asked Questions
    url: https://abyss.abgox.com/faq/
    about: Please check the frequently asked questions here.
contact_links:
  - name: Scoop Community Support
    url: https://github.com/ScoopInstaller/Scoop/discussions
    about: Please ask Scoop related questions here.
