name: 🔢 Hash Error
description: Open an issue about a package's hash is incorrect.
title: "xxx@x.x.x: hash check failed"
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: |
            I have used the predefined issue title.
            e.g. abgox.PSCompletions@5.5.0: hash check failed
          required: true
        - label: I have verified that I am using the latest version of Scoop and corresponding bucket.
          required: true
        - label: I have verified that this issue was created on GitHub.
