name: 📦 Package Update
description: Open an issue about a package update.
title: "[Request]: "
labels: ["package-update"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have searched all issues/PRs to ensure it has not already been reported or fixed.
          required: true
  - type: input
    attributes:
      label: Name
      description: Name of the package
      placeholder: e.g. Microsoft.VisualStudioCode
    validations:
      required: true
  - type: textarea
    attributes:
      label: What's New
      description: Clear and concise details of what it is
    validations:
      required: true
