name: 📦 Package Request
description: Open an issue about a missing package.
title: "[Request]: "
labels: ["package-request"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have searched all issues/PRs to ensure it has not already been reported or fixed.
          required: true
  - type: input
    attributes:
      label: Name
      description: Name of the package
      placeholder: e.g. Microsoft.VisualStudioCode
    validations:
      required: true
  - type: input
    attributes:
      label: Name in winget-pkgs
      description: Name of the package in [winget-pkgs](https://github.com/microsoft/winget-pkgs)
      placeholder: e.g. Microsoft.VisualStudioCode
  - type: input
    attributes:
      label: Description
      description: Clear and concise details of what it is
      placeholder: |
        一个轻量级、功能强大，插件生态丰富的文件编辑器
        A lightweight but powerful source code editor.
    validations:
      required: true
  - type: input
    attributes:
      label: Homepage
      description: URI of the package's homepage
      placeholder: e.g. https://code.visualstudio.com/
    validations:
      required: true
  - type: input
    attributes:
      label: Repository
      description: URI of the package's repository
      placeholder: e.g. https://github.com/microsoft/vscode
  - type: input
    attributes:
      label: Download Link(s)
      description: URI(s) of the package's download(s)
      placeholder: |
        64bit: https://update.code.visualstudio.com/$version/win32-x64-archive/stable#/dl.7z
        arm64: https://update.code.visualstudio.com/$version/win32-arm64-archive/stable#/dl.7z
    validations:
      required: true
  - type: textarea
    attributes:
      label: Some Indication of Popularity/Repute
      description: GitHub stars/software reviews etc.
    validations:
      required: true
