name: Check Manifest

on:
  pull_request_target:
    types: [opened]
  issue_comment:
    types: [created] # /check

concurrency:
  group: check-manifest-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  check:
    name: Check Manifest
    runs-on: windows-latest
    if: |
      github.event_name == 'pull_request_target' ||
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        startsWith(github.event.comment.body, '/check') &&
        (
          github.event.comment.user.login == github.event.issue.user.login ||
          contains(
            fromJson('["OWNER","MEMBER","COLLABORATOR","CONTRIBUTOR"]'),
            github.event.comment.author_association
          )
        )
      )
    env:
      REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
      MARKER: "<!-- comment-by-bot-for-check-manifest -->"
    steps:
      - name: Find or create comment
        id: comment
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request?.number || context.payload.issue?.number
            const marker = process.env.MARKER
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              per_page: 100
            })

            let comment = comments.data.find(c => c.body && c.body.includes(marker))

            const body = `${marker}

            ⏳ Checking...
            `

            if (comment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
                body
              })
              core.setOutput("comment_id", comment.id)
            } else {
              const res = await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr,
                body
              })
              core.setOutput("comment_id", res.data.id)
            }

      - name: Check Manifest
        shell: pwsh
        run: |
          $repo = $env:REPO
          $pr = $env:PR_NUMBER
          $marker = $env:MARKER
          $headers = @{
              Authorization = "Bearer $env:GITHUB_TOKEN"
              Accept        = 'application/vnd.github.v3+json'
          }

          $api = "https://api.github.com/repos/$repo/pulls/$pr/files?per_page=100"

          $files = Invoke-RestMethod -Uri $api -Headers $headers

          $results = @()
          $has = $false

          Write-Host '::group::Manifests'

          foreach ($file in $files) {
              if ($file.filename -notmatch '^bucket.*/(.+)\.json$') {
                  continue
              }
              $has = $true
              $m = $matches[1]
              Write-Host $m

              $part = $m.Split('.', 2)
              $publisher = $part[0]
              $id = $part[1]
              $letter = $publisher.ToLower()[0]

              $c = Invoke-RestMethod -Uri $file.raw_url -Headers $headers

              $line = @()

              # homepage
              $line += if ($c.homepage) { "[$m]($($c.homepage))" } else { $m }

              # check winget package
              $path = "$letter/$($m.Replace('.', '/'))"
              $api = "https://api.github.com/repos/microsoft/winget-pkgs/contents/manifests/$path"
              $url = "https://github.com/microsoft/winget-pkgs/blob/master/manifests/$path"
              try {
                  $res = Invoke-RestMethod -Uri $api -Headers $headers -ErrorAction stop
                  $line += "[Yes]($url)"
              }
              catch {
                  $line += "[No]($url)"
              }

              # type
              $type = if ($c.psmodule) { 'psmodule' } elseif ($c.font) { 'font' } else { $null }
              $line += if ($type) { $type } else { '' }

              # persistence
              $persistence = @()
              if ($c.link -or $c.pre_install -match '(?<!#.*)(A-New-LinkFile|A-New-LinkDirectory)') { $persistence += 'link' }
              if ($c.persist) { $persistence += 'persist' }
              if ($persistence) {
                  $line += $persistence -join '<br />'
              }
              else {
                  $line += ''
              }

              $results += '|' + ($line -join '|') + '|'
          }
          Write-Host '::endgroup::'

          if ($has) {
              $results = @(
                  $marker,
                  '',
                  '| Manifest | In Winget | Type | Persistence |',
                  '| :-: | :-: | :-: | :-: |'
              ) + $results
          }
          else {
              $results = @(
                  $marker,
                  '',
                  'No manifests detected in this PR.'
              )
          }

          $results + @(
              '',
              '---',
              'Comment `/check` to run the check again.'
          ) | Out-File result.md

      - name: Comment PR
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('result.md', 'utf8');
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.comment.outputs.comment_id }},
              body: body
            });

      - name: Check rate limit
        shell: pwsh
        run: |
          # Check rate limit
          $headers = @{
              Authorization = "Bearer $env:GITHUB_TOKEN"
              Accept        = 'application/vnd.github.v3+json'
          }
          try {
              $response = Invoke-RestMethod -Uri 'https://api.github.com/rate_limit' -Headers $headers
              Write-Output $response.rate
          }
          catch {
              Write-Output 'Failed to check rate limit'
          }
