name: Check Winget Package in PR

on:
  pull_request_target:
    types: [opened]
  issue_comment:
    types: [created] # /check-winget

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  check:
    name: Check Winget Package
    runs-on: windows-latest
    if: github.event_name == 'pull_request_target' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.comment.body, '/check-winget'))
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get changed manifests
        id: manifests
        shell: pwsh
        run: |
          $pr = "${{ github.event.pull_request.number || github.event.issue.number }}"
          $repo = "${{ github.repository }}"

          $api = "https://api.github.com/repos/$repo/pulls/$pr/files?per_page=100"

          $headers = @{
            Authorization = "Bearer $env:GITHUB_TOKEN"
            Accept = "application/vnd.github.v3+json"
          }

          $files = Invoke-RestMethod -Uri $api -Headers $headers

          $manifests = @()

          foreach ($file in $files) {
            if ($file.filename -match '^bucket.*/(.+)\.json$') {
              $manifests += $matches[1]
            }
          }

          $manifests = $manifests | Sort-Object -Unique

          $manifests | Out-File manifests.txt

          Write-Host '::group::Manifests'
          Write-Host ($manifests -join "`n")
          Write-Host '::endgroup::'

      - name: Check winget
        id: check
        shell: pwsh
        run: |
          $results = @(
            '### Package in [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)',
            ''
          )

          $manifests = Get-Content manifests.txt

          if ($manifests) {
            $headers = @{
              Authorization = "Bearer $env:GITHUB_TOKEN"
              Accept = "application/vnd.github.v3+json"
            }
            foreach ($m in $manifests) {
              $path = "$($m.ToLower()[0])/$($m.Replace('.', '/'))"
              $api = "https://api.github.com/repos/microsoft/winget-pkgs/contents/manifests/$path"
              $url = "https://github.com/microsoft/winget-pkgs/blob/master/manifests/$path"
              try {
                $res = Invoke-RestMethod -Uri $api -Headers $headers -ErrorAction stop
                $results += "- [x] [$m]($url)"
              }
              catch {
                if ($_.Exception.Response.StatusCode -eq 404) {
                  $results += "- [ ] [$m]($url)"
                }
              }
            }
          }
          else {
            $results += 'No manifests detected in this PR.'
          }

          $results += @(
            '',
            '---',
            '> Comment `/check-winget` to run the check again.'
          )

          $results | Out-File result.md

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request?.number || context.payload.issue?.number;
            const fs = require('fs');
            const body = fs.readFileSync('result.md', 'utf8');

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body: body
            });
