name: Issues

on:
  issues:
    types: [opened]

jobs:
  issue-handler:
    name: Issue Handler
    runs-on: windows-latest
    if: ${{ !contains(github.event.issue.title, '[Bug]') && !contains(github.event.issue.title, '[Request]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.repository.default_branch}}

      - name: Issue Handler
        # uses: ScoopInstaller/GithubActions@main
        uses: abgox/ScoopInstaller-GithubActions@abyss
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync-repos:
    name: Sync Repos
    needs: issue-handler
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Latest Labels
        id: check_labels
        uses: actions/github-script@v9
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            const labels = issue.data.labels.map(l => l.name);
            console.log(`Current labels: ${labels}`);
            const result = labels.includes('hash-fix-needed') && labels.includes('verified');
            console.log(`Result: ${result}`);
            return result

      - name: Run Sync
        if: steps.check_labels.outputs.result == 'true'
        uses: abgox/hub-mirror-action@abgox
        continue-on-error: true
        with:
          src: github/abgox
          dst: gitee/abgox
          dst_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
          dst_token: ""
          force_update: true
          static_list: ${{ github.event.repository.name }}
