name: Sort JSON

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push-changes:
    name: Sort JSON and Push Changes
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.repository.default_branch}}
          fetch-depth: 50

      - name: Sort JSON and Push Changes
        shell: pwsh
        run: |
          $manual = "${{ github.event_name }}" -eq "workflow_dispatch"
          .\script\sort-json.ps1 -All:$manual
          .\script\push-change.ps1 -message "(chore): automatically sort json [skip ci]"

  sync-repos:
    name: Sync Repos
    needs: push-changes
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: abgox/hub-mirror-action@abgox
        with:
          src: github/abgox
          dst: gitee/abgox
          dst_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
          dst_token: ""
          force_update: true
          static_list: ${{ github.event.repository.name }}
